# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'BTMeshDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BTMeshDemo
  pod 'RxSwift'
  pod 'BTMesh', :git => 'https://github.com/marcosxray/BTMesh', :tag => '0.0.11'

  target 'BTMeshDemoTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'BTMesh', :git => 'https://github.com/marcosxray/BTMesh', :tag => '0.0.11'
  end

  target 'BTMeshDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
